### ISSUE TITLE
E steps callibration

### ISSUE THREAD

**Issue by sbaeder** [teachingtechYT/teachingtechYT.github.io#175]
Doesn't know how to handle LARGE or decimal input for steps.   I have a geared stepper and using micro stepping, I need a number like 470 to get 100mm extruded.

But overall, good site!

**Comment by sbaeder** [comment]
Looked at this more, and I think all we need to do is mover the multiplication to before the divide and add ()

OLD....
`function esteps(){
    var oldSteps = document.estepsForm.oldSteps.value;
    var remainingFil = document.estepsForm.remainingFil.value;
    var actualExtrusion = 120 - remainingFil;
    **var newSteps = (oldSteps/actualExtrusion*100).toFixed(2);**
    $("#e1").html(remainingFil);`
New...
`function esteps(){
    var oldSteps = document.estepsForm.oldSteps.value;
    var remainingFil = document.estepsForm.remainingFil.value;
    var actualExtrusion = 120 - remainingFil;
    **var newSteps = ((oldSteps*100)/actualExtrusion).toFixed(2);**
    $("#e1").html(remainingFil);
`

**Comment by teachingtechYT** [comment]
I'm sorry but I'm not sure what the problem is.
The calculator works with large or small e step values.
The proposed code change doesn't actually change the output due to mathematical order of operations.
Maybe you can reopen with information such as what you input, what you expect to receive and what you actually receive?
