### ISSUE TITLE
Baseline Print:  Acceptable Tolerances not clear

### ISSUE THREAD

**Issue by DonutATX** [teachingtechYT/teachingtechYT.github.io#184]
Did the baseline print, on my new BIQU B1, and started chasing hundredths of millimetres.  

I realized quickly that in the real world, with a cheap printer, there would be some slop.  I went looking for what acceptable tolerances were for this test, and it was challenging.  

If there was a section on "Tolerances and Expectations" that would be great.  

Thanks!

**Comment by teachingtechYT** [comment]
From the bottom of the page:
The cube should look similar to those at the top of this page. If there are no major issues, please continue to the next step. If there is a significant defect, the culprit will likely be found by working through the frame page.
This is a simple 'hello world' test print to find major issues. The page doesn't say anything about testing or measuring tolerances.
For your interest, since this issue was created a tab has been added for XYZ calibration.
