### ISSUE TITLE
E-Steps can't parse commas as decimal points

### ISSUE THREAD

**Issue by vguttmann** [teachingtechYT/teachingtechYT.github.io#205]
As I said, the page on E-Step calibration does not parse commas as decimal points, which gets even more confusing, because it does not say that, but simply assumes these values to be equal to zero.

I would prefer if that error was fixed, the page would throw an error, or if there at least was a bright red text telling the user to use only the point as a decimal point.

**Comment by teachingtechYT** [comment]
Perhaps there is a language barrier but I don't understand the problem. I'm aware that some languages use , and other use . as a decimal point. If you are using , instead of . isn't it just a matter of using . and then everything works?
Rather than complain about something so trivial, press a different key on the keyboard?
My apologies if I have misunderstood.
To make this even easier, the default values now add a redundant .0 on the end so it is clear that the form uses . rather than ,
