### ISSUE TITLE
Direct drive extruder retract too fast

### ISSUE THREAD

**Issue by maxduracell** [teachingtechYT/teachingtechYT.github.io#212]
While doing the retract test, my titan motor would buzz and jitter at 40mm/s and miss nearly every step.  I am able to command feeds and retracts from the terminal without issue and I even swapped from the pancake to a full size motor.  Both behaved similarly.  I attempted to slow down the acceleration to make the direction change softer, but the biggest gain was from slowing the overall speed. Not sure if this is an issue with the gcode, my machine, or if this is something I should have noticed and accounted for.

**Comment by teachingtechYT** [comment]
These tests give you the ability to set the exact retract/unretract speed from the form. Retraction acceleration is a possibility but none of the tests alter this.
That leaves me with two possibilities:
1. Some your printers is using different units. ie mm/sec vs mm/min This would result in a vastly different speed than expected.
2. Your firmware wants relative extrusion rather than the absolute used here.
3. Very hard for me to diagnose over the internet I'm sorry.
