### ISSUE TITLE
Baseline print retraction is 10x input

### ISSUE THREAD

**Issue by halogen25** [teachingtechYT/teachingtechYT.github.io#223]
This print stalled by clogging the Microswiss metal hotend.  I got so frustrated that I changed it out for the stock hotend. Then I saw the long spool of retracted filament between steps. Something is screwy I’m the code!

**Comment by teachingtechYT** [comment]
I can't recreate this and no one else has ever reported it, so it seems likely the problem is on your end.
Where did you come up with the 10x number? Have you opened and inspected the gcode?
![image](https://user-images.githubusercontent.com/8293825/125401028-f9a89600-e3f5-11eb-8cd5-cc52806965cb.png)
![image](https://user-images.githubusercontent.com/8293825/125401052-03ca9480-e3f6-11eb-96ce-fd71ce0403b4.png)
