### ISSUE TITLE
Different bed temperature

### ISSUE THREAD

**Issue by geromueller** [teachingtechYT/teachingtechYT.github.io#246]
Hi! For PETG on a glas bed I increase the bed temp from 60 to 65 after the first layer. This makes the print stick to the bed extremely well. Maybe you can add this to the gcode.

**Comment by teachingtechYT** [comment]
Please understand that I need to keep the interface as minimal as possible as to not confuse new users. Changing the bed temp on the 2nd layer is the exception rather than the rule. If 65 degrees works well for you, can't you just set the be temp to 65 for these tests? Obviously when you go back to your slicer you can revert to your favourite method.
