### ISSUE TITLE
Are all e-steps the same in all firmwares?

### ISSUE THREAD

**Issue by staffert** [teachingtechYT/teachingtechYT.github.io#271]
Big fan of TT, keep up the great work.

...that aside, I have a question about e-steps and how (why) when I received my brand new CR-10s Pro V2, it came with an e-step setting of 140 already in the firmware, but being the engineer, I promptly found thisgreat tuning page and went to work. Sure enough, the correct number of steps was indeed 140!
Fantastic. An the printer went on to print a number of parts quite well, as advertised.

A little later, I also watched the TT video on firmware upgrades and decided to install the TinyMachines3D firmware for many reasons, and it too, seemed to work wonders for the system. 
Although SOMETHING happened, I'm not sure how or what exactly, the X-axis gantry seemed VERY off level and all of a sudden could NOT get a first layer down properly. I managed to get the X-axis back to normal, but no amount of bed leveling/X axis adjustment/software slicer setting, nozzle replacement, bowden tube issues, extruder gears could get me a first layer that was good.... nothing worked. So I looked at the e-steps in my firmware, still set to 140, even post upgrade....and I start to think, "maybe I should re-calibrate the e-steps".

Well, I did, and it is now set to 320!?! Back to working perfectly.

So, my real question is: 
Is there a known difference in the way Marlin calculates e-steps from for original default Creality firmware (v1.70.0) vs. TM3D (v2.0.5)?

**Comment by teachingtechYT** [comment]
Both are still Marlin, however it would seem one of the versions has something different going on. My guess is that the microstepping is different. If for instance the microstepping was set to 1/32 instead of 1/16, the e steps would change.
As a further answer to your question, Marlin and RRF handle es steps the same way, but Klipper uses a different metric. The e steps calculator on here still works for Klipper though. Put in old value plus filament remaining and the new value will ready to substiture into printer.cfg.
