### ISSUE TITLE
Z axis problem

### ISSUE THREAD

**Issue by Israel-Tomas** [teachingtechYT/teachingtechYT.github.io#281]
I did the calibration with the 20x20x20 cube and it was good, however when I did it with the 40x40x40 cube, the Z however got 35, I made a piece with 140mm and it was good, then I made a piece with the Z of 40 however got 25mm, what could be happening?

Cube 20x20x20 e cube 20x20x40  however got 25

![WhatsApp Image 2021-03-16 at 08 38 02](https://user-images.githubusercontent.com/65759858/112291334-c8516200-8c6e-11eb-8448-e7059fa77ed4.jpeg)

140mm piece

![WhatsApp Image 2021-03-16 at 08 38 02 (1)](https://user-images.githubusercontent.com/65759858/112290988-7f99a900-8c6e-11eb-8203-90546fa3de95.jpeg)

peça com o Z de 40mm ,mas ficou com 25mm...

![WhatsApp Image 2021-03-14 at 08 44 27 (1)](https://user-images.githubusercontent.com/65759858/112291167-a35cef00-8c6e-11eb-8bc5-993d9f31081c.jpeg)

Cube 40x40x40 however got Z 35mm

![WhatsApp Image 2021-03-19 at 18 39 19](https://user-images.githubusercontent.com/65759858/112292042-765d0c00-8c6f-11eb-9eaa-b2031641eeea.jpeg)

**Comment by teachingtechYT** [comment]
The 20mm cube I assume is sliced by this site. The other parts are sliced by you with your slicer. Clearly the problem is with your slicer profile if the 20mm cube from this site is accurate but nothing else is.
I wish you luck solving your problem but I don't believe it has anything to do with here.
