### ISSUE TITLE
Order of operations recommendation. 

### ISSUE THREAD

**Issue by CS22332615** [teachingtechYT/teachingtechYT.github.io#292]
I would like to suggest that the xyz steps calibration follow the frame check followed by the e-steps calibration. I think it’s important that the mechanical aspects be squared away so that subsequent calibration dealing with flow and slicer extrusion variables can be adjusted for dimensional accuracy. Also I’d like to suggest that when setting the xyz step values that the values be evenly divisible by .04. In doing so, you avoid rounding error related micro-stepping. You may have covered this already. You have the best and most accurate website on the topic and I regularly refer new owners to it.

**Comment by teachingtechYT** [comment]
I respectfully disagree. There is definitely merit to your process and it will give the best results possible, but most users will never calibrate XYZ steps because the accuracy their printer produces is sufficient. Also keep in mind a dial gauge is a relatively expensive tool. The combination of these two means I consider this an optional step, and that's why I have it at the end.
