### ISSUE TITLE
Checking 'Strip ALL original start gcode and use only custom gcode instead' adds 'undefined' Symbol in gcode-file

### ISSUE THREAD

**Issue by KoeRt888** [teachingtechYT/teachingtechYT.github.io#340]
Hi,

I'm using Klipper and have a start code macro to let the bed heat up for 5 minutes to wait for the expansion of the aluminum bed. When I try to use it as only means as start gcode the generator on the 'First Layer' calibration page it adds a 'undefined' symbol to the gcode-file. I don't know if this happens in every calibration page form or just the one of 'First Layer'.

First try to copy my start code macros:
![teachingTech_onlyStartCode](https://user-images.githubusercontent.com/65965320/127757158-65f5ed24-d1fb-4988-92ef-fa8fc1ec6760.png)

Try to copy it from notepad++ to the field with an additional CR LF:
![teachingTech_onlyStartCode_CRLF](https://user-images.githubusercontent.com/65965320/127757183-70f466d2-9db3-4a4a-ac09-861b358b442b.png)

result in the downloaded gcode:
![teachingTech_onlyStartCode_CRLF_gcode](https://user-images.githubusercontent.com/65965320/127757189-e0aaf631-ad6f-4869-8447-ecb2da13ed71.png)

Is this a symbol that is added via javascript, or is has it something to do with encoding of the string pasted to the field from Slicer software (SuperSlicer) to browser?

**Comment by teachingtechYT** [comment]
That is a bug specific to the first layer test that I've been unable to find the cause of. It happens when a variable is refrencing in the gcode procesing that does exist or can't be accessed.
It's been there since the V2 rewrite but typically was tacked on to the end of a comment so was never read by the machine. Using the strip start gcode seems to expose on its own line. Thanks for the report, I'll do some digging.

**Comment by teachingtechYT** [comment]
Fixed!
