### ISSUE TITLE
Feature request: Support structure setting calibration 

### ISSUE THREAD

**Issue by beng92** [teachingtechYT/teachingtechYT.github.io#353]
Would it be possible to include a support structure calibration tool. It could include values for support wall flow rate, gap between support and model, support density. The model to slice wouldn't have to be complicated - maybe a pillar with 4 bridges and an overhang

**Comment by teachingtechYT** [comment]
This has been requeste before but the problem comes from the differences between slicers. This site is based on S3D gcode, so even if the user dialed everything in perfectly with a test, this probably wouldn't translate to other slicers. All of the tests on this site suffer from this to some extent but support structures are on another level.
So sorry, it won't be effective enough to implement, despite definitely being an area of need.
