### ISSUE TITLE
Calculation between volume and length

### ISSUE THREAD

**Issue by Zogar89** [teachingtechYT/teachingtechYT.github.io#72]
In some slicers like Cura, some parameters are expressed in volume instead of mm as the additional distance when returning from a retraction.

I think a volume-distance calculator that takes into account nozzle size would be very useful on that tab.

I'm not sure if I should use the nozzle diameter or the filament diameter for the calculation.

**Comment by teachingtechYT** [comment]
I'm all for making it more accurate, but I don't necessarily want a separate calculator tab.
As far as I know, the only setting on this site that is affected by this is the extra restart distance on the retraction page.
Maybe there is a way to have a double output so Cura users have the needed value in volume rather than length.
